language: node_js
node_js:
  - 14

cache:
  yarn: true
  directories:
    - public
    - .cache

install:
  - yarn install

env: 
  CI: false

script:
  # - yarn test
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  target_branch: gh-pages
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main