name: portfolio_website_CD(continues deployment)
env:
  CI: false
  user_name: 'github-actions[bot]'
  user_email: 'github-actions[bot]@users.noreply.github.com'
  github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
  repository: ${{ github.repository }}
  # GITHUB_USERNAME: ${{ github.repository_owner }}
  # REACT_APP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is automatically set by Github Actions
  # USE_GITHUB_DATA: "true"
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # Build the Project
        run: |
          npm install
          npm run predeploy
      - name: Deploy 🚀
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy